# HDR-AUTO-GENERATED: TaskCreated
# This file can be safely overwritten by TaskCreated.
# Regenerate: rerun the command or script that instantiates TaskCreated for this task.
# Do not edit this file by hand.

from pydantic import Field
from hdr.tasks.std import Task
from move_support import MoveContext, MovePurpose


class MoveChosen(Task):
    """Represents one chosen conceptual move in a language-agnostic outline, validated as a reader-state transition along one contrast axis."""

    context: MoveContext = Field(
        description="Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable"
    )
    purpose: MovePurpose = Field(
        description="Whether the move builds concrete pressure or shifts the reader's interpretive lens"
    )
    content: str = Field(
        description="Atomic outline sentence chosen for the move; it is not final prose"
    )
    contrast: str = Field(
        description="Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'"
    )
    before: str = Field(
        description="Relevant local reader lens before this move, focused only on the dimension the move changes"
    )
    after: str = Field(
        description="Relevant local reader lens after this move, focused on the same dimension as before and contrast"
    )

    def __init__(self, **data):
        super().__init__(**data)
        if " vs " not in self.contrast:
            raise AssertionError(
                "contrast must use the form '<quality> vs <opposing quality>'"
            )
        contrast_parts = [part.strip() for part in self.contrast.split(" vs ")]
        if len(contrast_parts) != 2 or not all(contrast_parts):
            raise AssertionError(
                "contrast must contain exactly two non-empty opposing qualities"
            )
        if contrast_parts[0].lower() == contrast_parts[1].lower():
            raise AssertionError("contrast qualities must not be identical")
        for field_name in ("content", "before", "after"):
            if not getattr(self, field_name).strip():
                raise AssertionError(f"{field_name} must not be empty")
        self.verify("""The contrast is exactly one projected axis of opposing qualities. The second side is meaningfully equivalent to 'not the first side' but with sharper taste language. It must not combine two metrics, two unrelated properties, object names, or analogy labels.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = "The failure is not that the agent forgot to care; it is that 'careful' stayed soft instead of becoming an enforceable contract the harness could reject." # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'soft vs enforceable' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader sees the missing rollback as a matter of agent carefulness.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees the missing rollback as a soft constraint that needed an enforceable representation.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'The run was expensive and still missed the rollback step, so HDR should make completion more reliable.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'high cost vs low guarantee' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader notices the agent used a lot of tokens.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader wants a stronger guarantee.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""The content, before, and after all operate on the same axis named by contrast. Rich details in content are allowed only when they clarify or intensify that single axis. The move fails if it introduces a second independent contrast.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'A checklist in prose can remind the agent, but HDR makes the same requirement enforceable by putting it into a task object that construction can reject.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'soft vs enforceable' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader treats prose checklists as useful reminders for agent behavior.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees prose checklists as soft reminders and task objects as enforceable completion boundaries.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'A checklist in prose is fast to write, while a task object adds more syntax, more imports, and more setup work.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'soft vs enforceable' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader thinks prose is fast to write.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader thinks task objects add setup overhead.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""Given context and before, content plausibly causes after without a hidden reasoning step. Before and after must describe the same local reader lens, and after must be a meaningful cognition upgrade rather than a paraphrase, mood change, or unrelated fact.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'Once rollback is a field the task must satisfy, a missing rollback stops being a review comment and becomes a construction failure.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'post-hoc vs construction-time' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader treats missing rollback as feedback discovered after the agent claims completion.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees missing rollback as something the task can reject during construction before completion is accepted.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'HDR uses Python classes, which many developers already know from building ordinary applications.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'post-hoc vs construction-time' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader treats missing rollback as post-hoc feedback.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader remembers that Python classes are familiar.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""The move is necessary against target_meaning. A strong editor could not delete content from an excellent introduction without reducing tension, precision, inevitability, or comprehension. Vivid but decorative details fail.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'The rollback step can disappear inside a long agent run because prose asks for it, but nothing in the harness must hold it.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'requested vs held' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader assumes that asking for a rollback step gives the agent a durable obligation.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees that a prose request is not durable unless the harness holds the requirement as data.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'It is 11:47 p.m., the terminal cursor blinks, and the room feels quiet while the agent keeps working.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'quiet vs dramatic' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader has no image of the scene.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader imagines a late-night terminal scene.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""The move uses only concepts available from target_reader, prior moves, or concepts it explicitly introduces inside content. It must not rely on unexplained terms, distinctions, metaphors, or framework-specific meanings.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'Calling it a contract matters because this reader already knows software contracts: something either satisfies the shape and checks, or construction fails.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'suggestive vs contractual' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = "The reader hears 'careful' as a suggestive instruction." # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader connects HDR to the familiar idea of a contractual condition that can fail.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = "The move is basically a Curry-Howard proof term over the agent's latent meaning vector." # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'informal vs type-theoretic' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader thinks the agent needs clearer instructions.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader understands HDR as a proof-theoretic object.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""When purpose is BUILD, content creates concrete pressure using a real-looking mechanism, failure tendency, system behavior, or grounded detail that the target reader can immediately recognize. It must not be generic abstraction.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'The agent can edit five files, summarize the migration, and still leave rollback as a line nobody has to instantiate.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'soft vs enforceable' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader treats a detailed migration prompt as enough to make rollback part of the work.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees rollback as soft when it remains prose rather than an enforceable object field.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'Agents sometimes miss important requirements, so better validation can improve reliability.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'weak vs strong' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader knows agents can miss things.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader knows validation can help.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""When purpose is BUILD, every vivid detail in content is load-bearing. Removing the detail would weaken attention, mechanism understanding, pressure, or preparation for a later shift. Pure atmosphere fails.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = "A migration plan can name backfill timing, rollback, and verification commands in prose, yet none of those nouns are objects the harness must inspect before it accepts 'done'." # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'named vs inspected' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader treats named requirements in a plan as meaningful coverage.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees that naming requirements is weaker than making them inspectable by the harness.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'The migration plan sits in a long markdown file with neat headings, clean bullets, and a timestamp at the top.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'plain vs polished' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader imagines an ordinary markdown plan.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader imagines a better-formatted markdown plan.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""When purpose is BUILD, content must not resolve the target concept too early. It should prepare mental material that makes a later SHIFT needed, not define the whole target concept in advance.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'The missing rollback is not hard to phrase; it is hard to make unavoidable inside the agent loop.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'sayable vs unavoidable' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader sees rollback as something the prompt can mention.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees that mentioning rollback and making rollback unavoidable are different.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.BUILD: 'build'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'HDR solves this by representing the whole task as a Python class whose typed fields and semantic verifies must construct successfully.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'informal vs formal' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader does not know HDR yet.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader has already received the full HDR definition.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""When purpose is SHIFT, content changes the reader's interpretation of already-built material through the contrast axis. It is not another concrete detail, example, or standalone definition.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'The problem is not that the agent needs more reminders; the problem is that reminders are soft until the harness can reject the missing requirement.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'soft vs enforceable' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader reads the rollback miss as a reminder problem.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader reads the rollback miss as an enforceability problem.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'The same agent may also forget a verification command, a data owner, or a runtime estimate.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'soft vs enforceable' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader has seen one missed rollback example.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader has seen three more missed fields.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""When purpose is SHIFT, any abstraction in content is earned by target_reader or prior BUILD moves. The sentence may name a higher-level lens only when the context has supplied concrete material that makes the lens immediately legible.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'That is the contract gap: the prompt contains the requirement, but the harness has nothing enforceable to fail.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'suggestive vs contractual' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader sees the rollback miss as a loose instruction problem.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees it as a contract gap between what prose asks for and what the harness can fail.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'This is the contract gap between conversational semantics and harness-enforced completion.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'suggestive vs contractual' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader has not yet seen any concrete failure.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader understands a contract gap.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
        self.verify("""When purpose is SHIFT, after is an irreversible cognition upgrade from before. After accepting content, a capable target reader cannot honestly return to before without ignoring the stated distinction.

Example that PASSES (score 5):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'A checklist can ask for rollback, but a task field can make rollback absent in the only place that counts: construction.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'requested vs required' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader treats requested rollback and required rollback as roughly the same in an agent prompt.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader sees requested rollback and required rollback as different completion boundaries.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)

Example that FAILS (score 1):
MoveChosen(
  context = MoveContext(
    target_reader = MarkdownFileWritten(
      path = 'hdr_target_reader.md' # Path to the file
      content = '# Target Reader\\n\\nThe intended reader already knows:\\n\\n- AI agents that receive goals and use tools\\n- The definition `Agent = Model + Harness`\\n- Harnesses as the runtime framework around a model, including context window,\\n  memory, tool use, and control flow\\n- Python classes, runtime validation, and software contracts\\n- LLM prompts and responses\\n\\nThe intended reader does not already know HDR.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing what the intended reader already knows
    target_concept = 'HDR' # Concept the move chain is introducing
    target_meaning = MarkdownFileWritten(
      path = 'hdr_target_meaning.md' # Path to the file
      content = '# Target Meaning\\n\\nIntroduce HDR as a harness design pattern for agent work.\\n\\nThe reader should understand that ordinary prose instructions can make an agent\\nsound careful while still leaving completion soft. HDR changes the completion\\nboundary by representing the intended outcome as an explicit Python task object:\\ntyped fields hold required evidence, programmatic checks reject malformed shape,\\nand semantic `self.verify()` assertions reject missing meaning.\\n\\nBy the end, the reader should see HDR as the move from conversational promises\\nto enforceable construction. The agent is not merely asked to do better; it must\\nkeep working until the final task instance constructs successfully.\\n' # Content of the file, auto-filled from disk (cannot be manually assigned)
    ) # Markdown file describing the full conceptual payload the chain must express
    prior_moves =  [
    MoveSnapshot(
        purpose = <MovePurpose.BUILD: 'build'> # Purpose of a previously chosen move
        content = 'A careful-looking agent run can still leave rollback as a sentence in the prompt instead of something the harness can reject.' # Atomic outline sentence chosen for that move
        contrast = 'soft vs enforceable' # Single projected contrast axis for that move
        before = 'The reader treats a detailed prompt and a long tool-using run as a reasonable completion boundary.' # Relevant reader lens before that move
        after = 'The reader sees that prose-bound requirements stay soft unless the harness has something enforceable to reject.' # Relevant reader lens after that move
      ),
    ] # Previously chosen moves, stored as snapshots to avoid recursive task generation
  ) # Target reader, target concept, target meaning, and prior moves that make necessity and continuity checkable
  purpose = <MovePurpose.SHIFT: 'shift'> # Whether the move builds concrete pressure or shifts the reader's interpretive lens
  content = 'HDR can make agent workflows more reliable by adding stronger validation checks.' # Atomic outline sentence chosen for the move; it is not final prose
  contrast = 'weak vs strong' # Single projected contrast axis, written as opposing qualities such as 'soft vs enforceable'
  before = 'The reader thinks validation can help reliability.' # Relevant local reader lens before this move, focused only on the dimension the move changes
  after = 'The reader thinks stronger validation can help reliability.' # Relevant local reader lens after this move, focused on the same dimension as before and contrast
)""")
