"""
Meta-contract for creating well-formed HDR contracts.

Contract validates contract definitions at construction time and generates
complete contract class code with examples embedded in verify conditions.
"""

import ast
import re
from typing import Any
from pydantic import Field, BaseModel, model_validator
from hdr.contracts.std import BaseContract, Example, quote
from hdr.contracts.coding import PythonFile


AUTO_GENERATED_FLAG = "# HDR-AUTO-GENERATED: Contract"
AUTO_GENERATED_HEADER = f"""{AUTO_GENERATED_FLAG}
# This file can be safely overwritten by Contract.
# Regenerate: rerun the command or script that instantiates Contract for this contract.
# Do not edit this file by hand.
"""
DEFAULT_IMPORTS = [
    "from pydantic import Field",
    "from hdr.contracts.std import BaseContract",
]


class FieldSpec(BaseModel):
    """Specification for a single field in a contract."""

    name: str = Field(description="Name of the field")
    type_annotation: str = Field(
        description="Type annotation as a string (e.g., 'str', 'list[int]', 'File')"
    )
    description: str = Field(
        description="Human-readable description of what this field represents"
    )
    default: str | None = Field(
        default=None,
        description="Default value as a string expression, or None if required",
    )


class VerifySpec(BaseModel):
    """Specification for a single verify call with required examples."""

    condition: str = Field(description="The condition text to verify")
    applies_when: str | None = Field(
        default=None,
        description=(
            "Optional Python expression evaluated on the generated contract instance; "
            "when present, the LLM verify only runs if this expression is true"
        ),
    )
    positive_example: dict[str, Any] = Field(
        description="Field values that should score 5 (definitely true)"
    )
    negative_example: dict[str, Any] = Field(
        description="Field values that should score 1 (definitely false)"
    )


class Contract(BaseContract):
    """
    Meta-contract for defining well-formed HDR contracts.

    Validates that:
    - All fields have descriptions (programmatic)
    - All verify specs have valid positive and negative examples (LLM-verified at instantiation)

    Provides code generation that embeds validated examples into verify conditions.
    Automatically generates a PythonFile for the created contract class,
    ensuring the file passes PyRight and Ruff checks.
    """

    class_name: str = Field(description="Name of the contract class to create")
    parent_class: str = Field(
        default="BaseContract", description="Parent class to inherit from"
    )
    docstring: str = Field(description="Docstring for the contract class")
    imports: list[str] = Field(
        default_factory=lambda: DEFAULT_IMPORTS.copy(),
        description="List of import statements to include at the top of the file",
    )
    fields: list[FieldSpec] = Field(description="List of field specifications")
    programmatic_checks: list[str] = Field(
        default_factory=list,
        description="Python code snippets for programmatic validations, executed before LLM verifies",
    )
    verifies: list[VerifySpec] = Field(
        description="List of verify specifications with examples"
    )
    generated_file: PythonFile | None = Field(
        init=False,
        frozen=True,
        default=None,
        description="The generated Python file instance, after successful creation (cannot be manually assigned). Will always be non-None after successful initialization.",
    )

    @model_validator(mode="before")
    @classmethod
    def _generate_file(cls, data: Any) -> Any:
        if not isinstance(data, dict):
            return data

        data = dict(data)
        data.pop("generated_file", None)

        class_name = data.get("class_name")
        if not isinstance(class_name, str):
            return data
        if "docstring" not in data or "fields" not in data or "verifies" not in data:
            return data

        fields = [FieldSpec.model_validate(field) for field in data.get("fields", [])]
        verifies = [
            VerifySpec.model_validate(verify) for verify in data.get("verifies", [])
        ]
        imports = list(data.get("imports", DEFAULT_IMPORTS))
        parent_class = str(data.get("parent_class", "BaseContract"))
        docstring = str(data.get("docstring", ""))
        programmatic_checks = list(data.get("programmatic_checks", []))

        cls._validate_task_spec(class_name, fields, verifies)

        file_content = cls._generate_file_content_for(
            imports=imports,
            class_name=class_name,
            parent_class=parent_class,
            docstring=docstring,
            fields=fields,
            programmatic_checks=programmatic_checks,
            verifies=verifies,
        )
        file_path = cls._generate_file_path_for(class_name)
        cls._write_generated_file(file_path, file_content)

        data["fields"] = fields
        data["verifies"] = verifies
        data["imports"] = imports
        data["generated_file"] = PythonFile(path=file_path)
        return data

    def __init__(self, **data):
        self._raise_if_existing_unmarked(data)
        self._raise_invalid_task_spec(data)
        super().__init__(**data)

        # LLM verification: validate each example against its condition
        for i, verify_spec in enumerate(self.verifies):
            pos_quoted = quote(self._to_example(verify_spec.positive_example))
            neg_quoted = quote(self._to_example(verify_spec.negative_example))

            pos_condition = (
                f"Given the contract object:\n{pos_quoted}\n\n"
                f"This condition holds true: {verify_spec.condition}"
            )
            self.llm_verify(pos_condition, expected_score=5, inject_self_quote=False)

            neg_condition = (
                f"Given the contract object:\n{neg_quoted}\n\n"
                f"This condition holds true: {verify_spec.condition}"
            )
            self.llm_verify(neg_condition, expected_score=1, inject_self_quote=False)

    @classmethod
    def _raise_if_existing_unmarked(cls, data: dict[str, Any]) -> None:
        class_name = data.get("class_name")
        if not isinstance(class_name, str):
            return

        file_path = cls._generate_file_path_for(class_name)
        first_line = cls._existing_file_first_line(file_path)
        if first_line and first_line != AUTO_GENERATED_FLAG:
            raise AssertionError(
                f"Refusing to overwrite existing file at {file_path}. "
                f"Only files starting with {AUTO_GENERATED_FLAG!r} can be regenerated."
            )

    @classmethod
    def _raise_invalid_task_spec(cls, data: dict[str, Any]) -> None:
        class_name = data.get("class_name")
        if not isinstance(class_name, str):
            return
        if "fields" not in data or "verifies" not in data:
            return

        fields = [FieldSpec.model_validate(field) for field in data.get("fields", [])]
        verifies = [
            VerifySpec.model_validate(verify) for verify in data.get("verifies", [])
        ]
        cls._validate_task_spec(class_name, fields, verifies)

    @classmethod
    def _validate_task_spec(
        cls, class_name: str, fields: list[FieldSpec], verifies: list[VerifySpec]
    ) -> None:
        if not class_name.isidentifier():
            raise AssertionError(
                f"Class name '{class_name}' is not a valid Python identifier."
            )

        for field_spec in fields:
            if not field_spec.description or not field_spec.description.strip():
                raise AssertionError(
                    f"Field '{field_spec.name}' is missing a description. "
                    f"All fields must have descriptions for HDR contracts."
                )
            if not field_spec.name.isidentifier():
                raise AssertionError(
                    f"Field name '{field_spec.name}' is not a valid Python identifier."
                )

        required_fields = {f.name for f in fields if f.default is None}
        all_fields = {f.name for f in fields}

        for i, verify_spec in enumerate(verifies):
            cls._validate_applies_when(i, verify_spec)
            for label, example in [
                ("positive_example", verify_spec.positive_example),
                ("negative_example", verify_spec.negative_example),
            ]:
                provided = set(example.keys())
                missing = required_fields - provided
                if missing:
                    raise AssertionError(
                        f"Verify #{i + 1} {label} is missing required fields: {missing}"
                    )
                extra = provided - all_fields
                if extra:
                    raise AssertionError(
                        f"Verify #{i + 1} {label} has unknown fields: {extra}"
                    )

    @staticmethod
    def _validate_applies_when(index: int, verify_spec: VerifySpec) -> None:
        if verify_spec.applies_when is None:
            return

        if not verify_spec.applies_when.strip():
            raise AssertionError(f"Verify #{index + 1} applies_when must not be empty")

        try:
            ast.parse(verify_spec.applies_when, mode="eval")
        except SyntaxError as exc:
            raise AssertionError(
                f"Verify #{index + 1} applies_when must be a valid Python expression"
            ) from exc

    def _to_example(self, values: dict[str, Any]) -> Example:
        """Convert a dict of field values into an Example for quoting."""
        return self._to_example_for(self.class_name, self.fields, values)

    @staticmethod
    def _to_example_for(
        class_name: str, fields: list[FieldSpec], values: dict[str, Any]
    ) -> Example:
        field_descs = {f.name: f.description for f in fields}
        return Example(
            class_name=class_name,
            fields={
                name: (value, field_descs.get(name, ""))
                for name, value in values.items()
            },
        )

    def _camel_to_snake(self, s: str) -> str:
        """Convert CamelCase to snake_case."""
        return self._camel_to_snake_value(s)

    @staticmethod
    def _camel_to_snake_value(s: str) -> str:
        s = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", s)
        return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s).lower()

    def _generate_file_content(self) -> str:
        """Generate the complete Python file content including imports and class code."""
        return self._generate_file_content_for(
            imports=self.imports,
            class_name=self.class_name,
            parent_class=self.parent_class,
            docstring=self.docstring,
            fields=self.fields,
            programmatic_checks=self.programmatic_checks,
            verifies=self.verifies,
        )

    @classmethod
    def _generate_file_content_for(
        cls,
        imports: list[str],
        class_name: str,
        parent_class: str,
        docstring: str,
        fields: list[FieldSpec],
        programmatic_checks: list[str],
        verifies: list[VerifySpec],
    ) -> str:
        lines = [AUTO_GENERATED_HEADER.rstrip(), ""]
        lines.extend(imports)
        lines.append("")
        lines.append(
            cls._generate_code_for(
                class_name=class_name,
                parent_class=parent_class,
                docstring=docstring,
                fields=fields,
                programmatic_checks=programmatic_checks,
                verifies=verifies,
            )
        )
        return "\n".join(lines)

    def _generate_file_path(self) -> str:
        """Generate the snake_case .py filename from the class name."""
        return self._generate_file_path_for(self.class_name)

    @classmethod
    def _generate_file_path_for(cls, class_name: str) -> str:
        """Generate the snake_case .py filename from the class name."""
        return f"{cls._camel_to_snake_value(class_name)}.py"

    def _generate_code(self) -> str:
        """
        Generate the complete Python code for the contract class.

        Programmatic checks come first, then LLM verifies with embedded examples.
        """
        return self._generate_code_for(
            class_name=self.class_name,
            parent_class=self.parent_class,
            docstring=self.docstring,
            fields=self.fields,
            programmatic_checks=self.programmatic_checks,
            verifies=self.verifies,
        )

    @classmethod
    def _generate_code_for(
        cls,
        class_name: str,
        parent_class: str,
        docstring: str,
        fields: list[FieldSpec],
        programmatic_checks: list[str],
        verifies: list[VerifySpec],
    ) -> str:
        """
        Generate the complete Python code for the contract class.

        Programmatic checks come first, then LLM verifies with embedded examples.
        """
        lines = []

        # Class definition
        lines.append(f"class {class_name}({parent_class}):")

        # Docstring
        if docstring:
            docstring_lines = docstring.strip().split("\n")
            if len(docstring_lines) == 1:
                lines.append(f'    """{docstring_lines[0]}"""')
            else:
                lines.append('    """')
                for doc_line in docstring_lines:
                    lines.append(f"    {doc_line}")
                lines.append('    """')
        lines.append("")

        # Fields
        for field_spec in fields:
            if field_spec.default is not None:
                lines.append(
                    f"    {field_spec.name}: {field_spec.type_annotation} = "
                    f'Field(default={field_spec.default}, description="{_escape(field_spec.description)}")'
                )
            else:
                lines.append(
                    f"    {field_spec.name}: {field_spec.type_annotation} = "
                    f'Field(description="{_escape(field_spec.description)}")'
                )
        lines.append("")

        # __init__
        lines.append("    def __init__(self, **data):")
        lines.append("        super().__init__(**data)")

        has_content = bool(programmatic_checks) or bool(verifies)

        if not has_content:
            lines.append("        pass")
        else:
            # Programmatic checks first (faster validation)
            for check in programmatic_checks:
                for check_line in check.strip().split("\n"):
                    lines.append(f"        {check_line}")

            # LLM verifies with embedded examples
            for verify_spec in verifies:
                condition_with_examples = cls._build_condition_with_examples_for(
                    class_name, fields, verify_spec
                )
                escaped = _escape_multiline(condition_with_examples)
                if verify_spec.applies_when:
                    lines.append(f"        if {verify_spec.applies_when.strip()}:")
                    lines.append(f"            self.llm_verify({escaped})")
                else:
                    lines.append(f"        self.llm_verify({escaped})")

        return "\n".join(lines)

    def _build_condition_with_examples(self, verify_spec: VerifySpec) -> str:
        """Build a condition string with embedded examples."""
        return self._build_condition_with_examples_for(
            self.class_name, self.fields, verify_spec
        )

    @classmethod
    def _build_condition_with_examples_for(
        cls, class_name: str, fields: list[FieldSpec], verify_spec: VerifySpec
    ) -> str:
        """Build a condition string with embedded examples."""
        pos_quoted = quote(
            cls._to_example_for(class_name, fields, verify_spec.positive_example)
        )
        neg_quoted = quote(
            cls._to_example_for(class_name, fields, verify_spec.negative_example)
        )

        return (
            f"{verify_spec.condition}\n\n"
            f"Example that PASSES (score 5):\n{pos_quoted}\n\n"
            f"Example that FAILS (score 1):\n{neg_quoted}"
        )

    @classmethod
    def _write_generated_file(cls, file_path: str, file_content: str) -> None:
        first_line = cls._existing_file_first_line(file_path)

        if first_line and first_line != AUTO_GENERATED_FLAG:
            raise AssertionError(
                f"Refusing to overwrite existing file at {file_path}. "
                f"Only files starting with {AUTO_GENERATED_FLAG!r} can be regenerated."
            )

        with open(file_path, "w") as f:
            f.write(file_content)

    @staticmethod
    def _existing_file_first_line(file_path: str) -> str:
        try:
            with open(file_path, "r") as existing_file:
                return existing_file.readline().strip()
        except FileNotFoundError:
            return ""


def _escape(s: str) -> str:
    """Escape a string for use inside a double-quoted Python string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _escape_multiline(s: str) -> str:
    """Escape a string, using triple quotes if it contains newlines."""
    if "\n" in s:
        escaped = s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        return f'"""{escaped}"""'
    else:
        return f'"{_escape(s)}"'
